"""Storage-independent contract for account persistence."""

from typing import Dict, Optional, Protocol


class UserRepositoryContract(Protocol):
    """Behavior required by controllers regardless of the storage backend."""

    def authenticate(self, login: str, password: str) -> Optional[Dict]: ...

    def get_all_users(self) -> list[Dict]: ...

    def get_user_by_id(self, user_id: str) -> Optional[Dict]: ...

    def register(
        self, name: str, login: str, password: str
    ) -> tuple[bool, str, Optional[Dict]]: ...

    def save_preferences(self, user_id: str, preferences: Dict) -> bool: ...

    def update_display_name(self, user_id: str, name: str) -> bool: ...

    def change_password(
        self, user_id: str, current_password: str, new_password: str
    ) -> tuple[bool, str]: ...

    def update_role(self, user_id: str, role: str) -> bool: ...

    def update_status(self, user_id: str, status: str, reason: str = "") -> bool: ...

    def set_account_status(
        self, actor_role: str, user_id: str, status: str, reason: str = "",
        actor_id: str | None = None,
    ) -> bool: ...

    def get_ban_message(self, login: str) -> Optional[str]: ...

    def is_online(self) -> bool: ...

    def logout(self) -> bool: ...
